name: flutter_vikings
description: A new Flutter project.
publish_to: 'none'
version: 1.2.1+12101

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.4
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.4.5
  collection: ^1.16.0
  firebase_analytics: ^9.3.3
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  firebase_messaging: ^12.0.3
  firebase_remote_config: ^2.0.16
  flame: ^1.3.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.5
  flutter_local_notifications: ^9.8.0+1
  flutter_native_splash: ^2.2.7
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.1.1+1
  font_awesome_flutter: ^10.1.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  go_router: ^4.2.7
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.6.0
  package_info_plus: ^1.4.3+1
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  vector_math: ^2.1.2

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icons/launcherIcon_android.png'
  image_path_ios: 'assets/icons/launcherIcon_ios.png'
  adaptive_icon_background: '#ffffff'

flutter_native_splash:
  color: '#FFFFFF'
  color_dark: '#02192C'
  image: assets/images/logoWithText.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/games/dashing_vikings/
